### ISSUE TITLE
Can't load rails console

### ISSUE THREAD

**Issue by frank101m** [dkam/paapi#1]
Hello, I know that the gem is currently under development but when installing it, and opening a rails console, an error: cannot load such file -- paapi/locales (LoadError). Do you have any idea why is it throwing that error?

**Comment by dkam** [comment]
Hey @frank101m - because it very, very alpha :-)  I've pushed an update which should fix that.

**Comment by frank101m** [comment]
Thank you very much, if there is something that is currently missing it would be great for you to state it in the README file so that we can help you implementing it.
