### ISSUE TITLE
Comma missing @ paapi.rb MARKETPLACE definitions

### ISSUE THREAD

**Issue by crisdias** [dkam/paapi#7]
Hey there!I found a bug, a missing comma next to the Brazil definition (lib/pappi.rb, line 45) that was causing requests to this region to fail. I tried to push a request to github with the change but I am a total noob when it comes to helping projects on github.

Thanks for the great gem!

**Comment by dkam** [comment]
Thanks - I've merged the fix and pushed a new gem.
